name: Gradle Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      # Set up JDK 17 (or the version you are using)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      # Cache Gradle dependencies for faster builds
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Run the Gradle build and tests
      - name: Build and Test with Gradle
        run: ./gradlew clean build

      # Upload test results in case of failure for easier debugging
      - name: Upload Test Results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/reports/tests/test

  # This step will make the pull request unmergeable if tests fail
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Ensure Tests Pass
        run: ./gradlew test

        # Mark the PR as unmergeable if the tests fail
        if: failure()
        continue-on-error: false